"""create resumes resume_versions job_preparations

Revision ID: 32947e1ca540
Revises:
Create Date: 2026-08-10 11:30:33.720111

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "32947e1ca540"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resumes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resumes")),
    )
    op.create_table(
        "resume_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("resume_id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(source = 'original_upload') = (version_number = 1)",
            name=op.f("ck_resume_versions_original_upload_is_version_one"),
        ),
        sa.CheckConstraint(
            "source IN ('original_upload', 'applied')",
            name=op.f("ck_resume_versions_source_allowed_values"),
        ),
        sa.CheckConstraint(
            "version_number > 0", name=op.f("ck_resume_versions_version_number_positive")
        ),
        sa.ForeignKeyConstraint(
            ["resume_id"],
            ["resumes.id"],
            name=op.f("fk_resume_versions_resume_id_resumes"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resume_versions")),
        sa.UniqueConstraint(
            "resume_id", "version_number", name="uq_resume_versions_resume_id_version_number"
        ),
    )
    op.create_table(
        "job_preparations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_resume_version_id", sa.UUID(), nullable=False),
        sa.Column("applied_resume_version_id", sa.UUID(), nullable=True),
        sa.Column("job_title", sa.String(length=255), nullable=False),
        sa.Column("company", sa.String(length=255), nullable=True),
        sa.Column("job_description", sa.Text(), nullable=False),
        sa.Column("analysis_result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("career_conversation", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("tailoring_plan", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("post_apply_analysis", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("interview_preparation", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'completed' OR applied_resume_version_id IS NOT NULL",
            name=op.f("ck_job_preparations_completed_requires_applied_version"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'active', 'completed')",
            name=op.f("ck_job_preparations_status_allowed_values"),
        ),
        sa.ForeignKeyConstraint(
            ["applied_resume_version_id"],
            ["resume_versions.id"],
            name=op.f("fk_job_preparations_applied_resume_version_id_resume_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_resume_version_id"],
            ["resume_versions.id"],
            name=op.f("fk_job_preparations_source_resume_version_id_resume_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_preparations")),
    )
    op.create_index(
        "ix_job_preparations_applied_resume_version_id",
        "job_preparations",
        ["applied_resume_version_id"],
        unique=False,
    )
    op.create_index(
        "ix_job_preparations_source_resume_version_id",
        "job_preparations",
        ["source_resume_version_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_job_preparations_source_resume_version_id", table_name="job_preparations")
    op.drop_index("ix_job_preparations_applied_resume_version_id", table_name="job_preparations")
    op.drop_table("job_preparations")
    op.drop_table("resume_versions")
    op.drop_table("resumes")
    # ### end Alembic commands ###
