"""add job preparation checkpoint timestamps

Revision ID: c122c2e3a625
Revises: 32947e1ca540
Create Date: 2026-08-12 11:25:46.373099

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c122c2e3a625"
down_revision: str | Sequence[str] | None = "32947e1ca540"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "job_preparations",
        sa.Column("initial_analysis_completed_at", sa.TIMESTAMP(timezone=True), nullable=True),
    )
    op.add_column(
        "job_preparations",
        sa.Column("career_conversation_completed_at", sa.TIMESTAMP(timezone=True), nullable=True),
    )
    op.add_column(
        "job_preparations",
        sa.Column("tailoring_plan_completed_at", sa.TIMESTAMP(timezone=True), nullable=True),
    )
    op.add_column(
        "job_preparations", sa.Column("applied_at", sa.TIMESTAMP(timezone=True), nullable=True)
    )
    op.add_column(
        "job_preparations",
        sa.Column("post_apply_analysis_completed_at", sa.TIMESTAMP(timezone=True), nullable=True),
    )
    op.create_check_constraint(
        op.f("ck_job_preparations_applied_checkpoint_consistent"),
        "job_preparations",
        "(applied_resume_version_id IS NOT NULL) = (applied_at IS NOT NULL)",
    )
    op.create_check_constraint(
        op.f("ck_job_preparations_career_conversation_checkpoint_consistent"),
        "job_preparations",
        "(career_conversation IS NOT NULL) = (career_conversation_completed_at IS NOT NULL)",
    )
    op.create_check_constraint(
        op.f("ck_job_preparations_initial_analysis_checkpoint_consistent"),
        "job_preparations",
        "(analysis_result IS NOT NULL) = (initial_analysis_completed_at IS NOT NULL)",
    )
    op.create_check_constraint(
        op.f("ck_job_preparations_post_apply_analysis_checkpoint_consistent"),
        "job_preparations",
        "(post_apply_analysis IS NOT NULL) = (post_apply_analysis_completed_at IS NOT NULL)",
    )
    op.create_check_constraint(
        op.f("ck_job_preparations_tailoring_plan_checkpoint_consistent"),
        "job_preparations",
        "(tailoring_plan IS NOT NULL) = (tailoring_plan_completed_at IS NOT NULL)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("ck_job_preparations_tailoring_plan_checkpoint_consistent"),
        "job_preparations",
        type_="check",
    )
    op.drop_constraint(
        op.f("ck_job_preparations_post_apply_analysis_checkpoint_consistent"),
        "job_preparations",
        type_="check",
    )
    op.drop_constraint(
        op.f("ck_job_preparations_initial_analysis_checkpoint_consistent"),
        "job_preparations",
        type_="check",
    )
    op.drop_constraint(
        op.f("ck_job_preparations_career_conversation_checkpoint_consistent"),
        "job_preparations",
        type_="check",
    )
    op.drop_constraint(
        op.f("ck_job_preparations_applied_checkpoint_consistent"),
        "job_preparations",
        type_="check",
    )
    op.drop_column("job_preparations", "post_apply_analysis_completed_at")
    op.drop_column("job_preparations", "applied_at")
    op.drop_column("job_preparations", "tailoring_plan_completed_at")
    op.drop_column("job_preparations", "career_conversation_completed_at")
    op.drop_column("job_preparations", "initial_analysis_completed_at")
    # ### end Alembic commands ###
